env:
    - RUN_ENV=development
language: objective-c
xcode_project: Example/KalturaClient.xcodeproj
xcode_scheme: KalturaClient_Tests
osx_image: xcode9
xcode_sdk: iphonesimulator10.3
script: xcodebuild clean build test -workspace Example/KalturaClient.xcworkspace -scheme KalturaClient_Tests -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3.1'
notifications:
  email:
    recipients:
      - moshe.maor@kaltura.com
      - jess.portnoy@kaltura.com
      - Jonathan.Kanarek@kaltura.com
      - nir.belinky@kaltura.com
      - Rivka.Peleg@kaltura.com
    on_success: change
    on_failure: always
